=== raid-codex/champions/schemas/champion.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "slug": {
            "type": "string",
            "pattern": "^[a-z\\-]+$"
        },
        "faction": {
            "type": "object",
            "required": [
                "name",
                "slug",
                "website_link",
                "image_slug",
                "number_of_champions",
                "default_description",
                "seo"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "slug": {
                    "$ref": "#/definitions/slug"
                },
                "website_link": {
                    "type": "string"
                },
                "image_slug": {
                    "$ref": "#/definitions/slug"
                },
                "number_of_champions": {
                    "type": "integer"
                },
                "default_description": {
                    "type": "string"
                },
                "seo": {
                    "$ref": "#/definitions/seo"
                }
            }
        },
        "aura": {
            "type": "object",
            "required": [],
            "properties": {}
        },
        "skill": {
            "type": "object",
            "required": [],
            "properties": {}
        },
        "seo": {
            "type": "object",
            "required": [
                "title",
                "description",
                "keywords"
            ],
            "properties": {
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "characteristics": {
            "type": "object",
            "required": [
                "hp",
                "attack",
                "defense",
                "speed",
                "critical_rate",
                "critical_damage",
                "resistance",
                "accuracy"
            ],
            "properties": {
                "hp": {
                    "type": "integer"
                },
                "attack": {
                    "type": "integer"
                },
                "defense": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                },
                "critical_rate": {
                    "type": "number"
                },
                "critical_damage": {
                    "type": "number"
                },
                "resistance": {
                    "type": "integer"
                },
                "accuracy": {
                    "type": "integer"
                }
            }
        },
        "rating_value": {
            "type": "string",
            "enum": [
                "",
                "D",
                "C",
                "B",
                "A",
                "S",
                "SS"
            ]
        },
        "rating": {
            "type": "object",
            "required": [],
            "properties": {
                "overall": {
                    "$ref": "#/definitions/rating_value"
                },
                "campaign": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_offense": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_defense": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_without_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_with_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "ice_guardian": {
                    "$ref": "#/definitions/rating_value"
                },
                "dragon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spider": {
                    "$ref": "#/definitions/rating_value"
                },
                "fire_knight": {
                    "$ref": "#/definitions/rating_value"
                },
                "minotaur": {
                    "$ref": "#/definitions/rating_value"
                },
                "force_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "magic_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spirit_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "void_dungeon": {
                    "$ref": "#/definitions/rating_value"
                }
            }
        },
        "build": {
            "type": "object",
            "required": [],
            "properties": {}
        }
    },
    "type": "object",
    "required": [
        "name",
        "rarity",
        "element",
        "type",
        "rating",
        "slug",
        "characteristics",
        "auras",
        "skills",
        "faction",
        "faction_slug",
        "website_link",
        "image_slug",
        "seo",
        "default_description",
        "recommended_builds"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "rarity": {
            "type": "string",
            "enum": [
                "Common",
                "Uncommon",
                "Rare",
                "Epic",
                "Legendary"
            ]
        },
        "element": {
            "type": "string",
            "enum": [
                "Magic",
                "Force",
                "Void",
                "Spirit",
                ""
            ]
        },
        "type": {
            "type": "string",
            "enum": [
                "HP",
                "Attack",
                "Assist",
                "Def",
                ""
            ]
        },
        "rating": {
            "$ref": "#/definitions/rating"
        },
        "slug": {
            "$ref": "#/definitions/slug"
        },
        "characteristics": {
            "type": "object",
            "required": [
                "60"
            ],
            "properties": {
                "60": {
                    "$ref": "#/definitions/characteristics"
                }
            }
        },
        "auras": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/aura"
            }
        },
        "skills": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/skill"
            }
        },
        "faction": {
            "$ref": "#/definitions/faction"
        },
        "faction_slug": {
            "$ref": "#/definitions/slug"
        },
        "website_link": {
            "type": "string"
        },
        "image_slug": {
            "$ref": "#/definitions/slug"
        },
        "seo": {
            "$ref": "#/definitions/seo"
        },
        "default_description": {
            "type": "string"
        },
        "recommended_builds": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/build"
            }
        },
        "lore": {
            "type": "string",
            "pattern": "^<p>.+<\/p>$"
        }
    }
}

=== raid-codex/champions/export/current/altan.json
{
  "name": "Altan",
  "rarity": "Legendary",
  "element": "Magic",
  "type": "Def",
  "rating": {
    "overall": "B",
    "campaign": "S",
    "arena_offense": "B",
    "arena_defense": "B",
    "clan_boss_without_giant_slayer": "C",
    "clan_boss_with_giant_slayer": "C",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "B",
    "fire_knight": "C",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "C",
    "spirit_dungeon": "C",
    "void_dungeon": "C"
  },
  "slug": "altan",
  "characteristics": {
    "60": {
      "hp": 20145,
      "attack": 837,
      "defense": 1398,
      "speed": 102,
      "critical_rate": 0.15,
      "critical_damage": 0.57,
      "resistance": 50,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [],
  "faction": {
    "name": "Barbarians",
    "slug": "barbarians",
    "website_link": "/factions/barbarians/",
    "image_slug": "image-faction-barbarians",
    "number_of_champions": 0,
    "default_description": "Barbarians is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Barbarians is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Barbarians",
        "barbarians"
      ]
    }
  },
  "faction_slug": "barbarians",
  "website_link": "/champions/altan/",
  "image_slug": "image-champion-altan",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Altan is a legendary def champion from the faction Barbarians doing magic damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Altan",
      "altan"
    ]
  },
  "default_description": "Altan is a legendary def champion from the faction Barbarians doing magic damage",
  "recommended_builds": [],
  "lore": "<p>Once a warrior of near legendary prowess among his people, Altan enjoyed a life of adventure and debauchery. Like many other Barbarians, he served as a mercenary, battled rival warriors for glory and bragging rights. Even as he grew older, Altan’s prideful nature did not abate.</p><p>And though his strength began to wane, he still craved the same renown and the elation of battle. When accused of becoming old and weak, he did not just give the offenders a good thrashing but also vowed to face the dread dragon Hellrazor alone. Without a word, he gathered his arms and departed for the Beast’s mountain.</p><p>It is unknown what transpired in the Dragon’s lair, for Altan refuses to speak of it. Some say the Arbiter herself intervened and saved him from certain death. Whatever the case may have been, it was clear that Altan did not prevail - yet he did not perish either. When he emerged, the old Barbarian warrior appeared fused with dragonflame that will burn within him forever. He swore fealty to the Arbiter and her fight against the growing Shadow and served her chosen warriors ever since.</p>"
}

=== raid-codex/champions/export/current/ripper.json
{
  "name": "Ripper",
  "rarity": "Epic",
  "element": "Force",
  "type": "Attack",
  "rating": {
    "overall": "B",
    "campaign": "C",
    "arena_offense": "B",
    "arena_defense": "C",
    "clan_boss_without_giant_slayer": "C",
    "clan_boss_with_giant_slayer": "D",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "B",
    "fire_knight": "A",
    "minotaur": "B",
    "force_dungeon": "A",
    "magic_dungeon": "B",
    "spirit_dungeon": "A",
    "void_dungeon": "B"
  },
  "slug": "ripper",
  "characteristics": {
    "60": {
      "hp": 16020,
      "attack": 1299,
      "defense": 936,
      "speed": 96,
      "critical_rate": 0.15,
      "critical_damage": 0.6,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [],
  "faction": {
    "name": "Skinwalker",
    "slug": "skinwalker",
    "website_link": "/factions/skinwalker/",
    "image_slug": "image-faction-skinwalker",
    "number_of_champions": 0,
    "default_description": "Skinwalker is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Skinwalker is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Skinwalker",
        "skinwalker"
      ]
    }
  },
  "faction_slug": "skinwalker",
  "website_link": "/champions/ripper/",
  "image_slug": "image-champion-ripper",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Ripper is a epic attack champion from the faction Skinwalker doing force damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Ripper",
      "ripper"
    ]
  },
  "default_description": "Ripper is a epic attack champion from the faction Skinwalker doing force damage",
  "recommended_builds": [],
  "lore": "<p>Ripper spent several years as a paid gladiator in the City of Ireth. Killing his enemies for the joy of the screaming crowd, he gained glory and fame as one of the most ruthless and deadly warriors in Teleria – until the day that he lost his first fight in the arena.</p><p>Broken and bowed, he bared his neck for the killing blow. But the blow never came – the elf who beat him declared him a worthy foe, spared his life, and even returned his weapon to him to that he might leave the field with honor, all in the face of the jeering spectators.</p><p>Truly impressed by the valor of the elf, Ripper offered him any boon he might grant. No one knows with certainty what was asked – only that the next day Ripper departed Ireth in the direction of the Dark Ravine, and that where Wanderer appears, Ripper soon follows. Some speculate this is his task – to seek out Wanderer and bring the traitor’s head to Queen Eva to repay the elven debt of honor.</p>"
}

=== raid-codex/champions/export/current/redeemer.json
{
  "name": "Redeemer",
  "rarity": "Uncommon",
  "element": "",
  "type": "Attack",
  "rating": {
    "overall": "D",
    "campaign": "",
    "arena_offense": "",
    "arena_defense": "",
    "clan_boss_without_giant_slayer": "",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "",
    "dragon": "",
    "spider": "",
    "fire_knight": "",
    "minotaur": "",
    "force_dungeon": "",
    "magic_dungeon": "",
    "spirit_dungeon": "",
    "void_dungeon": ""
  },
  "slug": "redeemer",
  "characteristics": {
    "60": {
      "hp": 10905,
      "attack": 1024,
      "defense": 727,
      "speed": 92,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Split",
      "raw_description": "Attacks 1 enemy. Places a 25% [Increase ATK] buff on this Champion for 1 turn if this attack is critical.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Damage +10%",
      "slug": "split"
    },
    {
      "name": "Elven Blade",
      "raw_description": "Attacks 1 enemy. Has a 50% chance of placing a 2.5% [Poison] debuff for 2 turns.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Buff/Debuff Chance +10%<br>Lvl. 5 Buff/Debuff Chance +15%<br>Lvl. 6 Cooldown -1",
      "slug": "elven-blade"
    }
  ],
  "faction": {
    "name": "Dark Elves",
    "slug": "dark-elves",
    "website_link": "/factions/dark-elves/",
    "image_slug": "image-faction-dark-elves",
    "number_of_champions": 0,
    "default_description": "Dark Elves is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Dark Elves is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Dark Elves",
        "dark-elves"
      ]
    }
  },
  "faction_slug": "dark-elves",
  "website_link": "/champions/redeemer/",
  "image_slug": "image-champion-redeemer",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Redeemer is a uncommon attack champion from the faction Dark Elves. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Redeemer",
      "redeemer"
    ]
  },
  "default_description": "Redeemer is a uncommon attack champion from the faction Dark Elves",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/vrask.json
{
  "name": "Vrask",
  "rarity": "Epic",
  "element": "Spirit",
  "type": "HP",
  "rating": {
    "overall": "S",
    "campaign": "S",
    "arena_offense": "A",
    "arena_defense": "A",
    "clan_boss_without_giant_slayer": "S",
    "clan_boss_with_giant_slayer": "S",
    "ice_guardian": "S",
    "dragon": "S",
    "spider": "S",
    "fire_knight": "A",
    "minotaur": "S",
    "force_dungeon": "S",
    "magic_dungeon": "S",
    "spirit_dungeon": "S",
    "void_dungeon": "S"
  },
  "slug": "vrask",
  "characteristics": {
    "60": {
      "hp": 23460,
      "attack": 870,
      "defense": 870,
      "speed": 97,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 45,
      "accuracy": 0
    }
  },
  "auras": [
    {
      "raw_description": "Increases Ally DEF in Dungeons by 33%."
    }
  ],
  "skills": [
    {
      "name": "Whack",
      "raw_description": "Attacks 1 enemy. Fills this Champion's Turn Meter by 20% if this attack is critical.<br>Damage based on: [HP]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Damage +5%",
      "slug": "whack"
    },
    {
      "name": "Lightning Strike",
      "raw_description": "Attacks 1 enemy.<br>Damage based on: [HP]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +10%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Cooldown -1",
      "slug": "lightning-strike"
    },
    {
      "name": "Cannibalism",
      "raw_description": "Heals all allies by 10% of his MAX HP when he inflicts a critical hit.",
      "slug": "cannibalism"
    }
  ],
  "faction": {
    "name": "Orcs",
    "slug": "orcs",
    "website_link": "/factions/orcs/",
    "image_slug": "image-faction-orcs",
    "number_of_champions": 0,
    "default_description": "Orcs is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Orcs is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Orcs",
        "orcs"
      ]
    }
  },
  "faction_slug": "orcs",
  "website_link": "/champions/vrask/",
  "image_slug": "image-champion-vrask",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Vrask is a epic hp champion from the faction Orcs doing spirit damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Vrask",
      "vrask"
    ]
  },
  "default_description": "Vrask is a epic hp champion from the faction Orcs doing spirit damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/graybeard.json
{
  "name": "Graybeard",
  "rarity": "Rare",
  "element": "Magic",
  "type": "Def",
  "rating": {
    "overall": "B",
    "campaign": "B",
    "arena_offense": "B",
    "arena_defense": "B",
    "clan_boss_without_giant_slayer": "D",
    "clan_boss_with_giant_slayer": "D",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "B",
    "fire_knight": "D",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "C",
    "spirit_dungeon": "C",
    "void_dungeon": "B"
  },
  "slug": "graybeard",
  "characteristics": {
    "60": {
      "hp": 15525,
      "attack": 1024,
      "defense": 1112,
      "speed": 92,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 40,
      "accuracy": 0
    }
  },
  "auras": [
    {
      "raw_description": "Increases Ally DEF in Dungeons by 30%."
    }
  ],
  "skills": [
    {
      "name": "Expose Weakness",
      "raw_description": "Attacks 1 enemy. Has a 50% chance of placing a [Provoke] debuff for 1 turn.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Buff/Debuff Chance +5%<br>Lvl. 6 Buff/Debuff Chance +10%",
      "slug": "expose-weakness"
    },
    {
      "name": "Ice Crush",
      "raw_description": "Attacks all enemies. Has a 25% chance of placing a [Freeze] debuff for 1 turn. Damage inflicted is proportional to DEF.<br>Damage based on: [DEF]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Cooldown -1<br>Lvl. 6 Buff/Debuff Chance +10%<br>Lvl. 7 Cooldown -1",
      "slug": "ice-crush"
    },
    {
      "name": "Bring It On",
      "raw_description": "Places a [Shield] buff on this Champion for 2 turns. Has an 80% chance of placing a [Counterattack] buff on this Champion for 2 turns. removed.<br>Lvl. 2 Buff/Debuff Chance +10%<br>Lvl. 3 Buff/Debuff Chance +10%<br>Lvl. 4 Cooldown -1<br>Lvl. 5 Cooldown -1",
      "slug": "bring-it-on"
    }
  ],
  "faction": {
    "name": "Skinwalker",
    "slug": "skinwalker",
    "website_link": "/factions/skinwalker/",
    "image_slug": "image-faction-skinwalker",
    "number_of_champions": 0,
    "default_description": "Skinwalker is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Skinwalker is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Skinwalker",
        "skinwalker"
      ]
    }
  },
  "faction_slug": "skinwalker",
  "website_link": "/champions/graybeard/",
  "image_slug": "image-champion-graybeard",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Graybeard is a rare def champion from the faction Skinwalker doing magic damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Graybeard",
      "graybeard"
    ]
  },
  "default_description": "Graybeard is a rare def champion from the faction Skinwalker doing magic damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/foli.json
{
    "name": "Foli",
    "rarity": "Legendary",
    "element": "Magic",
    "type": "Attack",
    "rating": {
        "overall": "",
        "campaign": "",
        "arena_offense": "",
        "arena_defense": "",
        "clan_boss_without_giant_slayer": "",
        "clan_boss_with_giant_slayer": "",
        "ice_guardian": "",
        "dragon": "",
        "spider": "",
        "fire_knight": "",
        "minotaur": "",
        "force_dungeon": "",
        "magic_dungeon": "",
        "spirit_dungeon": "",
        "void_dungeon": ""
    },
    "slug": "foli",
    "characteristics": {
        "60": {
            "hp": 15030,
            "attack": 1476,
            "defense": 1101,
            "speed": 99,
            "critical_rate": 0.15,
            "critical_damage": 0.63,
            "resistance": 30,
            "accuracy": 0
        }
    },
    "auras": [],
    "skills": [],
    "faction": {
        "name": "Dark Elves",
        "slug": "dark-elves",
        "website_link": "/factions/dark-elves/",
        "image_slug": "image-faction-dark-elves",
        "number_of_champions": 0,
        "default_description": "Dark Elves is a faction from RAID Shadow Legends",
        "seo": {
            "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
            "description": "Dark Elves is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
            "keywords": [
                "raid",
                "shadow",
                "legends",
                "factions",
                "Dark Elves",
                "dark-elves"
            ]
        }
    },
    "faction_slug": "dark-elves",
    "website_link": "/champions/foli/",
    "image_slug": "image-champion-foli",
    "seo": {
        "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
        "description": "Foli is a legendary attack champion from the faction Dark Elves doing magic damage. Find out more on this Raid Shadow Legends codex.",
        "keywords": [
            "raid",
            "shadow",
            "legends",
            "champions",
            "tier",
            "list",
            "Foli",
            "foli"
        ]
    },
    "default_description": "Foli is a legendary attack champion from the faction Dark Elves doing magic damage",
    "recommended_builds": []
}

=== raid-codex/champions/export/current/commander.json
{
  "name": "Commander",
  "rarity": "Uncommon",
  "element": "",
  "type": "Assist",
  "rating": {
    "overall": "D",
    "campaign": "",
    "arena_offense": "",
    "arena_defense": "",
    "clan_boss_without_giant_slayer": "",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "",
    "dragon": "",
    "spider": "",
    "fire_knight": "",
    "minotaur": "",
    "force_dungeon": "",
    "magic_dungeon": "",
    "spirit_dungeon": "",
    "void_dungeon": ""
  },
  "slug": "commander",
  "characteristics": {
    "60": {
      "hp": 15690,
      "attack": 936,
      "defense": 771,
      "speed": 101,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Holy Fire",
      "raw_description": "Attacks 1 enemy. Has a 15% chance of placing a [Stun] debuff for 1 turn.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Buff/Debuff Chance +5%<br>Lvl. 6 Damage +10%<br>Lvl. 7 Damage +10%<br>Lvl. 8 Buff/Debuff Chance +5%",
      "slug": "holy-fire"
    },
    {
      "name": "Quickheal",
      "raw_description": "Heals the ally with the lowest HP by 40% of this Champion's HP. Completely fills the target's Turn Meter if the ally is fully healed. This Champion's Turn Meter cannot be filled by this Skill.<br>Lvl. 2 Heal +5%<br>Lvl. 3 Heal +5%<br>Lvl. 4 Heal +5%<br>Lvl. 5 Heal +10%<br>Lvl. 6 Cooldown -1<br>Lvl. 7 Cooldown -1",
      "slug": "quickheal"
    }
  ],
  "faction": {
    "name": "Banner-Lords",
    "slug": "banner-lords",
    "website_link": "/factions/banner-lords/",
    "image_slug": "image-faction-banner-lords",
    "number_of_champions": 0,
    "default_description": "Banner Lords is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Banner Lords is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Banner Lords",
        "banner-lords"
      ]
    }
  },
  "faction_slug": "banner-lords",
  "website_link": "/champions/commander/",
  "image_slug": "image-champion-commander",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Commander is a uncommon support champion from the faction Banner Lords. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Commander",
      "commander"
    ]
  },
  "default_description": "Commander is a uncommon support champion from the faction Banner Lords",
  "recommended_builds": [],
  "lore": ""
}
