=== raid-codex/champions/schemas/champion.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "slug": {
            "type": "string",
            "pattern": "^[a-z\\-]+$"
        },
        "faction": {
            "type": "object",
            "required": [
                "name",
                "slug",
                "website_link",
                "image_slug",
                "number_of_champions",
                "default_description",
                "seo"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "slug": {
                    "$ref": "#/definitions/slug"
                },
                "website_link": {
                    "type": "string"
                },
                "image_slug": {
                    "$ref": "#/definitions/slug"
                },
                "number_of_champions": {
                    "type": "integer"
                },
                "default_description": {
                    "type": "string"
                },
                "seo": {
                    "$ref": "#/definitions/seo"
                }
            }
        },
        "aura": {
            "type": "object",
            "required": [],
            "properties": {}
        },
        "skill": {
            "type": "object",
            "required": [],
            "properties": {}
        },
        "seo": {
            "type": "object",
            "required": [
                "title",
                "description",
                "keywords"
            ],
            "properties": {
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "characteristics": {
            "type": "object",
            "required": [
                "hp",
                "attack",
                "defense",
                "speed",
                "critical_rate",
                "critical_damage",
                "resistance",
                "accuracy"
            ],
            "properties": {
                "hp": {
                    "type": "integer"
                },
                "attack": {
                    "type": "integer"
                },
                "defense": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                },
                "critical_rate": {
                    "type": "number"
                },
                "critical_damage": {
                    "type": "number"
                },
                "resistance": {
                    "type": "integer"
                },
                "accuracy": {
                    "type": "integer"
                }
            }
        },
        "rating_value": {
            "type": "string",
            "enum": [
                "",
                "D",
                "C",
                "B",
                "A",
                "S",
                "SS"
            ]
        },
        "rating": {
            "type": "object",
            "required": [],
            "properties": {
                "overall": {
                    "$ref": "#/definitions/rating_value"
                },
                "campaign": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_offense": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_defense": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_without_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_with_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "ice_guardian": {
                    "$ref": "#/definitions/rating_value"
                },
                "dragon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spider": {
                    "$ref": "#/definitions/rating_value"
                },
                "fire_knight": {
                    "$ref": "#/definitions/rating_value"
                },
                "minotaur": {
                    "$ref": "#/definitions/rating_value"
                },
                "force_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "magic_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spirit_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "void_dungeon": {
                    "$ref": "#/definitions/rating_value"
                }
            }
        },
        "build": {
            "type": "object",
            "required": [],
            "properties": {}
        }
    },
    "type": "object",
    "required": [
        "name",
        "rarity",
        "element",
        "type",
        "rating",
        "slug",
        "characteristics",
        "auras",
        "skills",
        "faction",
        "faction_slug",
        "website_link",
        "image_slug",
        "seo",
        "default_description",
        "recommended_builds"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "rarity": {
            "type": "string",
            "enum": [
                "Common",
                "Uncommon",
                "Rare",
                "Epic",
                "Legendary"
            ]
        },
        "element": {
            "type": "string",
            "enum": [
                "Magic",
                "Force",
                "Void",
                "Spirit",
                ""
            ]
        },
        "type": {
            "type": "string",
            "enum": [
                "HP",
                "Attack",
                "Assist",
                "Def",
                ""
            ]
        },
        "rating": {
            "$ref": "#/definitions/rating"
        },
        "slug": {
            "$ref": "#/definitions/slug"
        },
        "characteristics": {
            "type": "object",
            "required": [
                "60"
            ],
            "properties": {
                "60": {
                    "$ref": "#/definitions/characteristics"
                }
            }
        },
        "auras": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/aura"
            }
        },
        "skills": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/skill"
            }
        },
        "faction": {
            "$ref": "#/definitions/faction"
        },
        "faction_slug": {
            "$ref": "#/definitions/slug"
        },
        "website_link": {
            "type": "string"
        },
        "image_slug": {
            "$ref": "#/definitions/slug"
        },
        "seo": {
            "$ref": "#/definitions/seo"
        },
        "default_description": {
            "type": "string"
        },
        "recommended_builds": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/build"
            }
        },
        "lore": {
            "type": "string",
            "pattern": "^<p>.+<\/p>$"
        }
    }
}

=== raid-codex/champions/export/current/shamrock.json
{
  "name": "Shamrock",
  "rarity": "Legendary",
  "element": "Spirit",
  "type": "Assist",
  "rating": {
    "overall": "A",
    "campaign": "C",
    "arena_offense": "S",
    "arena_defense": "S",
    "clan_boss_without_giant_slayer": "B",
    "clan_boss_with_giant_slayer": "B",
    "ice_guardian": "A",
    "dragon": "A",
    "spider": "C",
    "fire_knight": "C",
    "minotaur": "A",
    "force_dungeon": "B",
    "magic_dungeon": "A",
    "spirit_dungeon": "C",
    "void_dungeon": "B"
  },
  "slug": "shamrock",
  "characteristics": {
    "60": {
      "hp": 20805,
      "attack": 1002,
      "defense": 1189,
      "speed": 111,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 40,
      "accuracy": 0
    }
  },
  "auras": [
    {
      "raw_description": "Increases Ally ACC in all Battles by 70."
    }
  ],
  "skills": [
    {
      "name": "Luck Swap",
      "raw_description": "Attacks 1 enemy 2 times. Has a 60% chance of removing 1 random buff from the target.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Buff/Debuff Chance +5%<br>Lvl. 5 Buff/Debuff Chance +10%",
      "slug": "luck-swap"
    },
    {
      "name": "Lucky Charms",
      "raw_description": "Places a 60% [Increase DEF] buff on all allies for 2 turns. Has a 50% chance of placing a 30% [Increase C. RATE] buff on all allies for 2 turns. Also has a 25% chance of placing a 15% [Continuous Heal] buff on all allies for 2 turns if the [increase C. RATE] buff is placed. Has a 5% chance of placing a [Block Debuffs] buff on all allies for 2 turns if the [Continuous Heal] buff is placed.<br>Lvl. 2 Buff/Debuff Chance +5%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Buff/Debuff Chance +5%<br>Lvl. 5 Buff/Debuff Chance +5%<br>Lvl. 6 Cooldown -1",
      "slug": "lucky-charms"
    },
    {
      "name": "Uncatchable",
      "raw_description": "Places a 30% [Decrease SPD] debuff on all enemies for 2 turns. Decreases the Turn Meter of all enemies by 15%. Has a 10% chance of decreasing the Turn Meter of all enemies by a further 15%.<br>Lvl. 2 Cooldown -1",
      "slug": "uncatchable"
    }
  ],
  "faction": {
    "name": "Ogryn-Tribes",
    "slug": "ogryn-tribes",
    "website_link": "/factions/ogryn-tribes/",
    "image_slug": "image-faction-ogryn-tribes",
    "number_of_champions": 0,
    "default_description": "Ogryn-Tribes is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Ogryn-Tribes is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Ogryn-Tribes",
        "ogryn-tribes"
      ]
    }
  },
  "faction_slug": "ogryn-tribes",
  "website_link": "/champions/shamrock/",
  "image_slug": "image-champion-shamrock",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Shamrock is a legendary assist champion from the faction Ogryn-Tribes doing spirit damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Shamrock",
      "shamrock"
    ]
  },
  "default_description": "Shamrock is a legendary assist champion from the faction Ogryn-Tribes doing spirit damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/jaeger.json
{
  "name": "Jaeger",
  "rarity": "Uncommon",
  "element": "",
  "type": "Attack",
  "rating": {
    "overall": "D",
    "campaign": "",
    "arena_offense": "",
    "arena_defense": "",
    "clan_boss_without_giant_slayer": "",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "",
    "dragon": "",
    "spider": "",
    "fire_knight": "",
    "minotaur": "",
    "force_dungeon": "",
    "magic_dungeon": "",
    "spirit_dungeon": "",
    "void_dungeon": ""
  },
  "slug": "jaeger",
  "characteristics": {
    "60": {
      "hp": 14370,
      "attack": 1200,
      "defense": 595,
      "speed": 100,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Shackle Shot",
      "raw_description": "Attacks 1 enemy. Has a 10% chance of placing a 15% [Decrease SPD] debuff for 1 turn.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Buff/Debuff Chance +5%<br>Lvl. 5 Buff/Debuff Chance +10%",
      "slug": "shackle-shot"
    },
    {
      "name": "Freezing Arrow",
      "raw_description": "Attacks 1 enemy. Has a 30% chance of placing a [Freeze] debuff for 1 turn.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Buff/Debuff Chance +10%<br>Lvl. 6 Buff/Debuff Chance +20%<br>Lvl. 7 Cooldown -1",
      "slug": "freezing-arrow"
    }
  ],
  "faction": {
    "name": "High Elves",
    "slug": "high-elves",
    "website_link": "/factions/high-elves/",
    "image_slug": "image-faction-high-elves",
    "number_of_champions": 0,
    "default_description": "High Elves is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "High Elves is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "High Elves",
        "high-elves"
      ]
    }
  },
  "faction_slug": "high-elves",
  "website_link": "/champions/jaeger/",
  "image_slug": "image-champion-jaeger",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Jaeger is a uncommon attack champion from the faction High Elves. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Jaeger",
      "jaeger"
    ]
  },
  "default_description": "Jaeger is a uncommon attack champion from the faction High Elves",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/duelist.json
{
  "name": "Duelist",
  "rarity": "Uncommon",
  "element": "",
  "type": "Attack",
  "rating": {
    "overall": "D",
    "campaign": "",
    "arena_offense": "",
    "arena_defense": "",
    "clan_boss_without_giant_slayer": "",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "",
    "dragon": "",
    "spider": "",
    "fire_knight": "",
    "minotaur": "",
    "force_dungeon": "",
    "magic_dungeon": "",
    "spirit_dungeon": "",
    "void_dungeon": ""
  },
  "slug": "duelist",
  "characteristics": {
    "60": {
      "hp": 11400,
      "attack": 1200,
      "defense": 793,
      "speed": 101,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Elan",
      "raw_description": "Attacks 1 enemy. Heals by 20% of the damage inflicted.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Heal +10%<br>Lvl. 5 Damage +10%<br>Lvl. 6 Damage +15%<br>Lvl. 7 Heal +15%",
      "slug": "elan"
    },
    {
      "name": "Stunning Slice",
      "raw_description": "Attacks 1 enemy. Has a 50% chance of placing a [Stun] debuff for 1 turn.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Buff/Debuff Chance +10%<br>Lvl. 5 Damage +10%<br>Lvl. 6 Buff/Debuff Chance +15%<br>Lvl. 7 Damage +10%<br>Lvl. 8 Cooldown -1",
      "slug": "stunning-slice"
    }
  ],
  "faction": {
    "name": "Banner-Lords",
    "slug": "banner-lords",
    "website_link": "/factions/banner-lords/",
    "image_slug": "image-faction-banner-lords",
    "number_of_champions": 0,
    "default_description": "Banner Lords is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Banner Lords is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Banner Lords",
        "banner-lords"
      ]
    }
  },
  "faction_slug": "banner-lords",
  "website_link": "/champions/duelist/",
  "image_slug": "image-champion-duelist",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Duelist is a uncommon attack champion from the faction Banner Lords. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Duelist",
      "duelist"
    ]
  },
  "default_description": "Duelist is a uncommon attack champion from the faction Banner Lords",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/luthiea.json
{
  "name": "Luthiea",
  "rarity": "Epic",
  "element": "Force",
  "type": "Attack",
  "rating": {
    "overall": "A",
    "campaign": "B",
    "arena_offense": "A",
    "arena_defense": "B",
    "clan_boss_without_giant_slayer": "A",
    "clan_boss_with_giant_slayer": "A",
    "ice_guardian": "A",
    "dragon": "A",
    "spider": "A",
    "fire_knight": "B",
    "minotaur": "A",
    "force_dungeon": "B",
    "magic_dungeon": "B",
    "spirit_dungeon": "B",
    "void_dungeon": "A"
  },
  "slug": "luthiea",
  "characteristics": {
    "60": {
      "hp": 14370,
      "attack": 1277,
      "defense": 1068,
      "speed": 93,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 20
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Burning Arrow",
      "raw_description": "Attacks 1 enemy. Has a 30% chance of placing a 5% [Poison] debuff for 2 turns.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Buff/Debuff Chance +5%<br>Lvl. 5 Buff/Debuff Chance +5%<br>Lvl. 6 Buff/Debuff Chance +10%",
      "slug": "burning-arrow"
    },
    {
      "name": "Ice Shot",
      "raw_description": "Attacks 3 times at random. Each hit has a 25% chance of placing a [Freeze] debuff for 1 turn.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +10%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Cooldown -1",
      "slug": "ice-shot"
    },
    {
      "name": "Numbing Poison",
      "raw_description": "Attacks all enemies. Has a 75% chance of placing a 30% [Decrease SPD] debuff for 2 turns.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +10%<br>Lvl. 4 Buff/Debuff Chance +10%<br>Lvl. 5 Buff/Debuff Chance +15%<br>Lvl. 6 Cooldown -1",
      "slug": "numbing-poison"
    }
  ],
  "faction": {
    "name": "High Elves",
    "slug": "high-elves",
    "website_link": "/factions/high-elves/",
    "image_slug": "image-faction-high-elves",
    "number_of_champions": 0,
    "default_description": "High Elves is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "High Elves is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "High Elves",
        "high-elves"
      ]
    }
  },
  "faction_slug": "high-elves",
  "website_link": "/champions/luthiea/",
  "image_slug": "image-champion-luthiea",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Luthiea is a epic attack champion from the faction High Elves doing force damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Luthiea",
      "luthiea"
    ]
  },
  "default_description": "Luthiea is a epic attack champion from the faction High Elves doing force damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/malbranche.json
{
  "name": "Malbranche",
  "rarity": "Rare",
  "element": "Void",
  "type": "Attack",
  "rating": {
    "overall": "",
    "campaign": "",
    "arena_offense": "",
    "arena_defense": "",
    "clan_boss_without_giant_slayer": "",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "",
    "dragon": "",
    "spider": "",
    "fire_knight": "",
    "minotaur": "",
    "force_dungeon": "",
    "magic_dungeon": "",
    "spirit_dungeon": "",
    "void_dungeon": ""
  },
  "slug": "malbranche",
  "characteristics": {
    "60": {
      "hp": 14865,
      "attack": 1321,
      "defense": 716,
      "speed": 111,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [],
  "faction": {
    "name": "Demonspawn",
    "slug": "demonspawn",
    "website_link": "/factions/demonspawn/",
    "image_slug": "image-faction-demonspawn",
    "number_of_champions": 0,
    "default_description": "Demonspawn is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Demonspawn is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Demonspawn",
        "demonspawn"
      ],
      "structured_data": null
    }
  },
  "faction_slug": "demonspawn",
  "website_link": "/champions/malbranche/",
  "image_slug": "image-champion-malbranche",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Malbranche is a rare attack champion from the faction Demonspawn doing void damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Malbranche",
      "malbranche"
    ],
    "structured_data": [
      {
        "@context": "http://schema.org/",
        "@type": "Person",
        "affiliation": {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Demonspawn"
        },
        "description": "Member of the faction Demonspawn, Malbranche is a champion of Rare rarity and of Attack type",
        "image": "https://raid-codex.com/wp-content/uploads/champions/image-champion-malbranche.jpg",
        "name": "Malbranche",
        "url": "https://raid-codex.com/champions/malbranche/"
      }
    ]
  },
  "default_description": "Malbranche is a rare attack champion from the faction Demonspawn doing void damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/guardian.json
{
  "name": "Guardian",
  "rarity": "Rare",
  "element": "Spirit",
  "type": "HP",
  "rating": {
    "overall": "B",
    "campaign": "C",
    "arena_offense": "B",
    "arena_defense": "B",
    "clan_boss_without_giant_slayer": "D",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "C",
    "fire_knight": "B",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "A",
    "spirit_dungeon": "B",
    "void_dungeon": "B"
  },
  "slug": "guardian",
  "characteristics": {
    "60": {
      "hp": 19155,
      "attack": 826,
      "defense": 925,
      "speed": 96,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 40,
      "accuracy": 0
    }
  },
  "auras": [
    {
      "raw_description": "Increases Ally HP in Dungeons by 27%."
    }
  ],
  "skills": [
    {
      "name": "Chop",
      "raw_description": "Attacks 1 enemy. Has a 50% chance of decreasing the duration of all enemy buffs by 2 turns.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Buff/Debuff Chance +5%<br>Lvl. 6 Damage +5%<br>Lvl. 7 Buff/Debuff Chance +5%",
      "slug": "chop"
    },
    {
      "name": "Thunderclap",
      "raw_description": "Attacks 4 times at random. Each hit has a 30% chance of applying a [Block Buffs] debuff for 2 turns.<br>Damage based on: [ATK] [HP]<br>Lvl. 2 Damage +10%<br>Lvl. 3 Damage +10%<br>Lvl. 4 Buff/Debuff Chance +5%<br>Lvl. 5 Damage +10%<br>Lvl. 6 Cooldown -1",
      "slug": "thunderclap"
    },
    {
      "name": "Prayer",
      "raw_description": "Places a [Block Debuffs] buff and a [Counterattack] buff on this Champion for 2 turns. Also places a 15% [Continuous Heal] buff on this Champion for 2 turns.<br>Lvl. 2 Cooldown -1",
      "slug": "prayer"
    }
  ],
  "faction": {
    "name": "Knight Revenant",
    "slug": "knight-revenant",
    "website_link": "/factions/knight-revenant/",
    "image_slug": "image-faction-knight-revenant",
    "number_of_champions": 0,
    "default_description": "Knight Revenant is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Knight Revenant is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Knight Revenant",
        "knight-revenant"
      ]
    }
  },
  "faction_slug": "knight-revenant",
  "website_link": "/champions/guardian/",
  "image_slug": "image-champion-guardian",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Guardian is a rare hp champion from the faction Knight Revenant doing spirit damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Guardian",
      "guardian"
    ]
  },
  "default_description": "Guardian is a rare hp champion from the faction Knight Revenant doing spirit damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/big-un.json
{
  "name": "Big'Un",
  "rarity": "Legendary",
  "element": "Magic",
  "type": "Attack",
  "rating": {
    "overall": "S",
    "campaign": "SS",
    "arena_offense": "SS",
    "arena_defense": "SS",
    "clan_boss_without_giant_slayer": "C",
    "clan_boss_with_giant_slayer": "D",
    "ice_guardian": "SS",
    "dragon": "A",
    "spider": "SS",
    "fire_knight": "C",
    "minotaur": "S",
    "force_dungeon": "B",
    "magic_dungeon": "B",
    "spirit_dungeon": "C",
    "void_dungeon": "B"
  },
  "slug": "big-un",
  "characteristics": {
    "60": {
      "hp": 17505,
      "attack": 1575,
      "defense": 837,
      "speed": 104,
      "critical_rate": 0.15,
      "critical_damage": 0.63,
      "resistance": 30,
      "accuracy": 10
    }
  },
  "auras": [],
  "skills": [],
  "faction": {
    "name": "Ogryn-Tribes",
    "slug": "ogryn-tribes",
    "website_link": "/factions/ogryn-tribes/",
    "image_slug": "image-faction-ogryn-tribes",
    "number_of_champions": 0,
    "default_description": "Ogryn-Tribes is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Ogryn-Tribes is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Ogryn-Tribes",
        "ogryn-tribes"
      ]
    }
  },
  "faction_slug": "ogryn-tribes",
  "website_link": "/champions/big-un/",
  "image_slug": "image-champion-big-un",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Big'Un is a legendary attack champion from the faction Ogryn-Tribes doing magic damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Big'Un",
      "big-un"
    ]
  },
  "default_description": "Big'Un is a legendary attack champion from the faction Ogryn-Tribes doing magic damage",
  "recommended_builds": [],
  "lore": ""
}
