=== raid-codex/champions/schemas/champion.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "slug": {
            "type": "string",
            "pattern": "^[a-z\\-]+$"
        },
        "faction": {
            "type": "object",
            "required": [
                "name",
                "slug",
                "website_link",
                "image_slug",
                "number_of_champions",
                "default_description",
                "seo"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "slug": {
                    "$ref": "#/definitions/slug"
                },
                "website_link": {
                    "type": "string"
                },
                "image_slug": {
                    "$ref": "#/definitions/slug"
                },
                "number_of_champions": {
                    "type": "integer"
                },
                "default_description": {
                    "type": "string"
                },
                "seo": {
                    "$ref": "#/definitions/seo"
                }
            }
        },
        "aura": {
            "type": "object",
            "required": [],
            "properties": {}
        },
        "skill": {
            "type": "object",
            "required": [],
            "properties": {}
        },
        "seo": {
            "type": "object",
            "required": [
                "title",
                "description",
                "keywords"
            ],
            "properties": {
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "characteristics": {
            "type": "object",
            "required": [
                "hp",
                "attack",
                "defense",
                "speed",
                "critical_rate",
                "critical_damage",
                "resistance",
                "accuracy"
            ],
            "properties": {
                "hp": {
                    "type": "integer"
                },
                "attack": {
                    "type": "integer"
                },
                "defense": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                },
                "critical_rate": {
                    "type": "number"
                },
                "critical_damage": {
                    "type": "number"
                },
                "resistance": {
                    "type": "integer"
                },
                "accuracy": {
                    "type": "integer"
                }
            }
        },
        "rating_value": {
            "type": "string",
            "enum": [
                "",
                "D",
                "C",
                "B",
                "A",
                "S",
                "SS"
            ]
        },
        "rating": {
            "type": "object",
            "required": [],
            "properties": {
                "overall": {
                    "$ref": "#/definitions/rating_value"
                },
                "campaign": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_offense": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_defense": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_without_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_with_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "ice_guardian": {
                    "$ref": "#/definitions/rating_value"
                },
                "dragon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spider": {
                    "$ref": "#/definitions/rating_value"
                },
                "fire_knight": {
                    "$ref": "#/definitions/rating_value"
                },
                "minotaur": {
                    "$ref": "#/definitions/rating_value"
                },
                "force_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "magic_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spirit_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "void_dungeon": {
                    "$ref": "#/definitions/rating_value"
                }
            }
        },
        "build": {
            "type": "object",
            "required": [],
            "properties": {}
        }
    },
    "type": "object",
    "required": [
        "name",
        "rarity",
        "element",
        "type",
        "rating",
        "slug",
        "characteristics",
        "auras",
        "skills",
        "faction",
        "faction_slug",
        "website_link",
        "image_slug",
        "seo",
        "default_description",
        "recommended_builds"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "rarity": {
            "type": "string",
            "enum": [
                "Common",
                "Uncommon",
                "Rare",
                "Epic",
                "Legendary"
            ]
        },
        "element": {
            "type": "string",
            "enum": [
                "Magic",
                "Force",
                "Void",
                "Spirit",
                ""
            ]
        },
        "type": {
            "type": "string",
            "enum": [
                "HP",
                "Attack",
                "Assist",
                "Def",
                ""
            ]
        },
        "rating": {
            "$ref": "#/definitions/rating"
        },
        "slug": {
            "$ref": "#/definitions/slug"
        },
        "characteristics": {
            "type": "object",
            "required": [
                "60"
            ],
            "properties": {
                "60": {
                    "$ref": "#/definitions/characteristics"
                }
            }
        },
        "auras": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/aura"
            }
        },
        "skills": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/skill"
            }
        },
        "faction": {
            "$ref": "#/definitions/faction"
        },
        "faction_slug": {
            "$ref": "#/definitions/slug"
        },
        "website_link": {
            "type": "string"
        },
        "image_slug": {
            "$ref": "#/definitions/slug"
        },
        "seo": {
            "$ref": "#/definitions/seo"
        },
        "default_description": {
            "type": "string"
        },
        "recommended_builds": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/build"
            }
        },
        "lore": {
            "type": "string",
            "pattern": "^<p>.+<\/p>$"
        }
    }
}

=== raid-codex/champions/export/current/executioner.json
{
  "name": "Executioner",
  "rarity": "Rare",
  "element": "Magic",
  "type": "Def",
  "rating": {
    "overall": "A",
    "campaign": "S",
    "arena_offense": "A",
    "arena_defense": "A",
    "clan_boss_without_giant_slayer": "C",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "A",
    "dragon": "B",
    "spider": "B",
    "fire_knight": "D",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "C",
    "spirit_dungeon": "B",
    "void_dungeon": "B"
  },
  "slug": "executioner",
  "characteristics": {
    "60": {
      "hp": 14865,
      "attack": 782,
      "defense": 1255,
      "speed": 89,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 40,
      "accuracy": 0
    }
  },
  "auras": [
    {
      "raw_description": "Increases Ally DEF in all Battles by 17%."
    }
  ],
  "skills": [
    {
      "name": "Shield Bash",
      "raw_description": "Attacks 1 enemy. Has a 15% chance of placing a [Stun] debuff for 1 turn.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +10%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Buff/Debuff Chance +5%<br>Lvl. 6 Buff/Debuff Chance +5%",
      "slug": "shield-bash"
    },
    {
      "name": "Tumult",
      "raw_description": "Attacks all enemies. Decreases the Turn Meter by 20%. Has a 50% chance of placing a 15% [Decrease SPD] debuff for 2 turns.<br>Damage based on: [ATK] [DEF]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +10%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Buff/Debuff Chance +15%<br>Lvl. 6 Cooldown -1",
      "slug": "tumult"
    },
    {
      "name": "Schiltron",
      "raw_description": "Places a 60% [Increase DEF] buff and a [Counterattack] buff on this Champion for 3 turns.<br>Lvl. 2 Cooldown -1<br>Lvl. 3 Cooldown -1",
      "slug": "schiltron"
    }
  ],
  "faction": {
    "name": "Knight Revenant",
    "slug": "knight-revenant",
    "website_link": "/factions/knight-revenant/",
    "image_slug": "image-faction-knight-revenant",
    "number_of_champions": 0,
    "default_description": "Knight Revenant is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Knight Revenant is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Knight Revenant",
        "knight-revenant"
      ]
    }
  },
  "faction_slug": "knight-revenant",
  "website_link": "/champions/executioner/",
  "image_slug": "image-champion-executioner",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Executioner is a rare def champion from the faction Knight Revenant doing magic damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Executioner",
      "executioner"
    ]
  },
  "default_description": "Executioner is a rare def champion from the faction Knight Revenant doing magic damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/atur.json
{
  "name": "Atur",
  "rarity": "Epic",
  "element": "Magic",
  "type": "HP",
  "rating": {
    "overall": "C",
    "campaign": "B",
    "arena_offense": "B",
    "arena_defense": "C",
    "clan_boss_without_giant_slayer": "D",
    "clan_boss_with_giant_slayer": "D",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "D",
    "fire_knight": "C",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "C",
    "spirit_dungeon": "C",
    "void_dungeon": "B"
  },
  "slug": "atur",
  "characteristics": {
    "60": {
      "hp": 19980,
      "attack": 826,
      "defense": 1145,
      "speed": 96,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 45,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [],
  "faction": {
    "name": "Barbarians",
    "slug": "barbarians",
    "website_link": "/factions/barbarians/",
    "image_slug": "image-faction-barbarians",
    "number_of_champions": 0,
    "default_description": "Barbarians is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Barbarians is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Barbarians",
        "barbarians"
      ]
    }
  },
  "faction_slug": "barbarians",
  "website_link": "/champions/atur/",
  "image_slug": "image-champion-atur",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Atur is a epic hp champion from the faction Barbarians doing magic damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Atur",
      "atur"
    ]
  },
  "default_description": "Atur is a epic hp champion from the faction Barbarians doing magic damage",
  "recommended_builds": [],
  "lore": "<p>Even those that live the lives full of hardship and primal strife among the Barbarian tribes are not immune to love. Atur, one of the mightiest warriors of his tribe, has always been a vain and arrogant man. He had every right to be proud, of course, for none could face him in a battle of equals and walk away victorious. None, until he met Kallia, whose prowess and ability to fly into relentless fury are as immense as her beauty.</p><p>Neither of them truly remembers what sparked the conflict between them, both will, of course, blame their other half. Regardless of the truth of the matter, an argument went out of control, and a battle of words, in which even Atur himself admits he took a thorough thrashing, turned to fisticuffs. Here, their passion for a fight was evenly matched and soon turned to passion for each other.</p><p>Though Barbarians are not exactly sophisticated, if not outright crude, by the standards of Kaerok or Aravia, Atur’s and Kallia’s relationship still blossomed into something sweet and loving… in its own way. It is certainly as strong as the mountains that surround their home, and as wild as the sandstorms that sweep the Deadlands.</p>"
}

=== raid-codex/champions/export/current/seducer.json
{
  "name": "Seducer",
  "rarity": "Rare",
  "element": "Void",
  "type": "Def",
  "rating": {
    "overall": "B",
    "campaign": "C",
    "arena_offense": "A",
    "arena_defense": "S",
    "clan_boss_without_giant_slayer": "C",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "C",
    "fire_knight": "C",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "C",
    "spirit_dungeon": "C",
    "void_dungeon": "B"
  },
  "slug": "seducer",
  "characteristics": {
    "60": {
      "hp": 16185,
      "attack": 628,
      "defense": 1321,
      "speed": 95,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 40,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [],
  "faction": {
    "name": "Undead Hordes",
    "slug": "undead-hordes",
    "website_link": "/factions/undead-hordes/",
    "image_slug": "image-faction-undead-hordes",
    "number_of_champions": 0,
    "default_description": "Undead Hordes is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Undead Hordes is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Undead Hordes",
        "undead-hordes"
      ]
    }
  },
  "faction_slug": "undead-hordes",
  "website_link": "/champions/seducer/",
  "image_slug": "image-champion-seducer",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Seducer is a rare def champion from the faction Undead Hordes doing void damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Seducer",
      "seducer"
    ]
  },
  "default_description": "Seducer is a rare def champion from the faction Undead Hordes doing void damage",
  "recommended_builds": [],
  "lore": "<p>Where Lumaya brings us the purity of love, Siroth places his bets on the pure carnal desire. He tempts with excess and indulgence, pulling more and more willing servants into his net wherever he can. Such was the fate of a young noble of Kaerok, vain and greedy, he wished for nothing more than to better his position in power and lot in life. By the magic of Siroth’s necromancers, and by his own dark deeds he was granted a vampire’s “kiss”, turning into one of the undead beasts himself. But his pact with the Shadow stood firm, for the noble was allowed to retain his humanly looks that he so adored - for a time, at least.</p><p>One can only imagine this wicked Seducer’s shock and surprise when he was faced with another servant of Siroth, known as the Temptress. A child of a vampire and a mortal woman, she was as vain and self-assured as he was himself. And throughout all his attempts to gain the upper hand, the Seducer only succeeded in catching himself in his own trap. For even the darkest heart can sometimes be illuminated by Lumaya’s light, and he found himself hopelessly in love and at the whims of the woman he sought to outdo.</p><p>Still, it may not be such a horrible fate in the end, for despite their mutual viciousness and less than savoury practices, the two of them do go together as well as a werewolf and a full moon. That connection is hard to deny, and it overcomes even the deeply ingrained selfishness that both of them were so known for.</p>"
}

=== raid-codex/champions/export/current/ghostborn.json
{
  "name": "Ghostborn",
  "rarity": "Legendary",
  "element": "Spirit",
  "type": "Assist",
  "rating": {
    "overall": "S",
    "campaign": "A",
    "arena_offense": "S",
    "arena_defense": "A",
    "clan_boss_without_giant_slayer": "B",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "S",
    "dragon": "A",
    "spider": "SS",
    "fire_knight": "S",
    "minotaur": "A",
    "force_dungeon": "SS",
    "magic_dungeon": "B",
    "spirit_dungeon": "S",
    "void_dungeon": "B"
  },
  "slug": "ghostborn",
  "characteristics": {
    "60": {
      "hp": 18825,
      "attack": 1211,
      "defense": 1112,
      "speed": 101,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 40,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Energy Bolt",
      "raw_description": "Attacks 1 enemy. Has a 50% chance of placing a 60% [Decrease DEF] debuff for 2 turns.<br>Damage based on: [ATK]<br>Lvl. 2 Buff/Debuff Chance +10%<br>Lvl. 3 Buff/Debuff Chance +10%<br>Lvl. 4 Buff/Debuff Chance +10%<br>Lvl. 5 Buff/Debuff Chance +20%",
      "slug": "energy-bolt"
    },
    {
      "name": "Petrify",
      "raw_description": "Attacks all enemies. Has a 75% chance of placing a 100% [Heal Reduction] debuff for 2 turns.<br>Damage based on: [ATK] [SPD]<br>Lvl. 2 Buff/Debuff Chance +10%<br>Lvl. 3 Buff/Debuff Chance +15%<br>Lvl. 4 Cooldown -1",
      "slug": "petrify"
    },
    {
      "name": "Ancestral Spirits",
      "raw_description": "Attacks all enemies. Has a 75% chance of placing a 60% [Decrease DEF] debuff for 2 turns. This debuff cannot be resisted. Places a 50% [Increase ATK] buff on all allies for 2 turns.<br>Damage based on: [ATK]<br>Lvl. 2 Buff/Debuff Chance +10%<br>Lvl. 3 Buff/Debuff Chance +15%<br>Lvl. 4 Cooldown -1",
      "slug": "ancestral-spirits"
    }
  ],
  "faction": {
    "name": "Dark Elves",
    "slug": "dark-elves",
    "website_link": "/factions/dark-elves/",
    "image_slug": "image-faction-dark-elves",
    "number_of_champions": 0,
    "default_description": "Dark Elves is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Dark Elves is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Dark Elves",
        "dark-elves"
      ]
    }
  },
  "faction_slug": "dark-elves",
  "website_link": "/champions/ghostborn/",
  "image_slug": "image-champion-ghostborn",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Ghostborn is a legendary assist champion from the faction Dark Elves doing spirit damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Ghostborn",
      "ghostborn"
    ]
  },
  "default_description": "Ghostborn is a legendary assist champion from the faction Dark Elves doing spirit damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/champions/export/current/gator.json
{
  "name": "Gator",
  "rarity": "Rare",
  "element": "Magic",
  "type": "Assist",
  "rating": {
    "overall": "B",
    "campaign": "B",
    "arena_offense": "B",
    "arena_defense": "C",
    "clan_boss_without_giant_slayer": "C",
    "clan_boss_with_giant_slayer": "D",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "C",
    "fire_knight": "A",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "C",
    "spirit_dungeon": "A",
    "void_dungeon": "B"
  },
  "slug": "gator",
  "characteristics": {
    "60": {
      "hp": 16515,
      "attack": 892,
      "defense": 1046,
      "speed": 99,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [],
  "faction": {
    "name": "Lizardmen",
    "slug": "lizardmen",
    "website_link": "/factions/lizardmen/",
    "image_slug": "image-faction-lizardmen",
    "number_of_champions": 0,
    "default_description": "Lizardmen is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Lizardmen is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Lizardmen",
        "lizardmen"
      ]
    }
  },
  "faction_slug": "lizardmen",
  "website_link": "/champions/gator/",
  "image_slug": "image-champion-gator",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Gator is a rare assist champion from the faction Lizardmen doing magic damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Gator",
      "gator"
    ]
  },
  "default_description": "Gator is a rare assist champion from the faction Lizardmen doing magic damage",
  "recommended_builds": [],
  "lore": "<p>In his childhood, Gatorâ€™s magical ability was out of control - presenting a danger to himself and others. Were it not for a travelling magi belonging to the Coven, he would have likely killed himself with one failed spell or the other. But fate saw fit to give the young lizardman another chance and provide him with tutors open-minded enough to pass their knowledge to a creature many would not see as anything beyond a beast. Such good fortune was not wasted, and when Gator returned to his people, it was a full-fledged mage, well-versed in arts that not many shamans would dare to replicate.</p>"
}

=== raid-codex/champions/export/current/paragon.json
{
  "name": "Paragon",
  "rarity": "Rare",
  "element": "Void",
  "type": "Def",
  "rating": {
    "overall": "A",
    "campaign": "C",
    "arena_offense": "A",
    "arena_defense": "A",
    "clan_boss_without_giant_slayer": "B",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "C",
    "fire_knight": "S",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "C",
    "spirit_dungeon": "S",
    "void_dungeon": "B"
  },
  "slug": "paragon",
  "characteristics": {
    "60": {
      "hp": 14370,
      "attack": 958,
      "defense": 1112,
      "speed": 96,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Power Drain",
      "raw_description": "Attacks 1 enemy. Has a 50% chance of decreasing the target's Turn Meter by 10%. Damage inflicted is proportional to DEF.<br>Damage based on: [DEF]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Damage +5%",
      "slug": "power-drain"
    },
    {
      "name": "Damage Control",
      "raw_description": "Places an [Unkillable] buff and a 25% [Increase ATK] buff on a target ally for 2 turns.<br>Lvl. 2 Cooldown -1<br>Lvl. 3 Cooldown -1",
      "slug": "damage-control"
    },
    {
      "name": "Life Shackles",
      "raw_description": "Attacks 3 times at random. Each hit has a 30% chance of placing a 100% [Heal Reduction] debuff and a 50% [Decrease ATK] debuff for 2 turns. Damage inflicted is proportional to DEF.<br>Damage based on: [DEF]<br>Lvl. 2 Buff/Debuff Chance +5%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Buff/Debuff Chance +10%<br>Lvl. 5 Cooldown -1",
      "slug": "life-shackles"
    }
  ],
  "faction": {
    "name": "Dark Elves",
    "slug": "dark-elves",
    "website_link": "/factions/dark-elves/",
    "image_slug": "image-faction-dark-elves",
    "number_of_champions": 0,
    "default_description": "Dark Elves is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Dark Elves is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Dark Elves",
        "dark-elves"
      ]
    }
  },
  "faction_slug": "dark-elves",
  "website_link": "/champions/paragon/",
  "image_slug": "image-champion-paragon",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Paragon is a rare def champion from the faction Dark Elves doing void damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Paragon",
      "paragon"
    ]
  },
  "default_description": "Paragon is a rare def champion from the faction Dark Elves doing void damage",
  "recommended_builds": [],
  "lore": ""
}
